import type { Metadata } from "next";
import { Marmelad, Pacifico } from "next/font/google";
import "./globals.scss";

import { Next13NProgress } from "nextjs13-progress";

import Header from "@/components/Header/Header";

const marmelad = Marmelad({ subsets: ['cyrillic'], weight: '400' });
const pacifico = Pacifico({ subsets: ['cyrillic'], weight: '400', variable: '--font-secondary' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${marmelad.className} ${pacifico.variable}`}>
        <Header />
        <main>
          {children}
        </main>
        <Next13NProgress height={7} color="#29D" />
      </body>
    </html>
  );
}
